Moved dbg to dbg_test
The dbg executable has been moved to dbg_test.  This is done to
better model what the dbg repo creates AND to make it possible to
have dbg code in a dbg sub-directory later on.

Fixed `make depend` where a `make clobber all` and then `make depend`
would generate the following error:

```
make depend starting

cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -MM -I.. utf8_posix_map.c foo.c jparse.c jparse.tab.c dbg.c util.c mkiocccentry.c iocccsize.c fnamchk.c txzchk.c chkentry.c json_parse.c jstrencode.c jstrdecode.c rule_count.c location.c sanity.c test/utf8_test.c verge.c dyn_array.c test/dyn_test.c dbg_test.c test/jnum_chk.c jnum_gen.c test/jnum_test.c json_util.c jparse_main.c entry_util.c jsemtblgen.c soup/chk_sem_auth.c soup/chk_sem_info.c soup/chk_validate.c json_sem.c entry_time.c | ./soup/fmt_depend.sh >> Makefile
soup/chk_validate.c:38:10: fatal error: 'entry_time.h' file not found
         ^~~~~~~~~~~~~~
1 error generated.

make depend completed
```