Checkpoint validate formed_UTC
Added code to validate formed_UTC.

As a result, timestr_eq_tstamp(), test_formed_UTC(), and
test_formed_timestamp() were also added to entry_util.c

Added sem_member_value_time_t() to convert a JSON member
whose value is a timestamp digit string into a time_t timestamp.

There is a significant problem with using:

    -D_DEFAULT_SOURCE -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600

These defines prevent functions that were introduced into C post c99
from being compiled without a warning/error.  Take for example, the
use of timegm(3) in entry_util.c:

    cc -D_DEFAULT_SOURCE -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600 -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror -Wno-unused-command-line-argument -Wno-poison-system-directories -Wno-unreachable-code-break -Wno-padded -lm entry_util.c -c

will produce the following error:

    entry_util.c:1150:25: error: implicit declaration of function 'timegm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
	timestr_as_time_t = timegm(&timeptr);

Whereas this:

    cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror -Wno-unused-command-line-argument -Wno-poison-system-directories -Wno-unreachable-code-break -Wno-padded -lm entry_util.c -c

will compile successfully.

While we understand that certain older systems such as CentOS 7 need:

    -D_DEFAULT_SOURCE -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600

some of the time, other systems CANNOT use them as they force the compiler,
in certain cases, to process system header files as of -std=c99 were in effect
even though -std=gnu11 is being used.

Even where modern systems do not generate warnibngs/errors, the use
of those defines could have adverse impacts in system include files
that might be incompatible with the C standard library being invoked
by the --std flag.

The use of those CentOS 7 defines needs to be kept to an absolute
minimum OR CentOS 7 needs to be abandoned as a platform that can
compile this repo.

To address this somewhat, the following changes Makefile were made:

The ${STD_SRC} has been changed to:

    D_LEGACY= -D_DEFAULT_SOURCE -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600
    C_STD= -std=gnu11

The ${CFLAGS} is now:

    CFLAGS= ${C_STD} ${COPT} -pedantic ${WARN_FLAGS} ${LDFLAGS}

A new ${LEGACY_CFLAGS} was added:

    LEGACY_CFLAGS= ${D_LEGACY} ${CFLAGS

To compile this change, all compile lines with ${CC} use ${LEGACY_CFLAGS}
except for entry_util.o which uses ${CFLAGS}.

TODO: Open up a issue to convert as many uses of ${LEGACY_CFLAGS}
      to ${CFLAGS} as possible that allows Centos 7 to still compile,
      or decide to abandon CentOS 7 support for this repo.