Fix JSON_TREE path in chkentry_test.sh
If one were to do make test chkentry_test.sh would work fine because
ioccc_test.sh specified the JSON_TREE. If, however, one were to do
./test_ioccc/chkentry_test.sh they would get:

    ERROR: json_tree/auth.json/good for chkentry directory not found: ./jparse/test_jparse/test_JSON/auth.json/good

because the path was not updated when the files were moved (presumably
that is what happened).

Now running make test and chkentry_test.sh directly both work.